### PR TITLE
Styled components

### PR DESCRIPTION
**Pull request by curt4207**
Responsiveness needs fixes.

### CODE REVIEW

**Comment by ezbc** [comment]
image

Looks like you're close to the design Denis proposed! We didn't quite figure where to put the search bar. What do you think of adding it to the header?

So layout changes I see left:
1. Create a header that spans the page
2. Move the app title to the header
3. Move the search bar and location to the header
4. Move the sign in button to the header
5. Center all other components below the header

What do you think of these changes?

**Comment by ezbc** [comment]
The secondary theme text is easy to read! I like the contrast! 
image

The location and app title are hard to read in the primary theme. There's not enough contract between the text and the background. 
image

Could you update the text colors there to have a higher contrast?

**Comment by curt4207** [comment]
Ok I will thx

**Comment by curt4207** [comment]
Have you checked out the updated branch? I think I pushed it🤔

**Comment by curt4207** [comment]
For some reason I didn't even see your first message I only saw the second message. I'll look at moving the search to where your arrow is pointing.

**Pull request merged**
